### ISSUE TITLE
Mark whether a class is a subclass

### ISSUE THREAD

**Issue by mauricioaniche** [mauricioaniche/predicting-refactoring-ml#21]
We conjecture that having `is_subclass` as a feature can help the model in make better predictions. This is important as we are now able to collect way more data points from sub classes (see commit https://github.com/mauricioaniche/predicting-refactoring-ml/commit/de64fcf3e057f55fd922ed0757f01b849f2a5c3f).

This feature requires changes in the data collection as well as in the ML pipeline.

**Comment by mauricioaniche** [comment]
The `is_subclass` attribute should go to the `ClassMetric` class.

**Comment by jan-gerling** [comment]
I would like to claim this issue.

**Comment by mauricioaniche** [comment]
PR was merged. Closing this issue.
