### ISSUE TITLE
Do not delete refactorings that we could not collect process metrics

### ISSUE THREAD

**Issue by mauricioaniche** [mauricioaniche/predicting-refactoring-ml#22]
Right now, we delete all data points of which we were not able to collect the process metrics. They are rare cases, but in scale, they happen a lot.

Let's not delete those cases, so that we have more data points. We thus need to filter them out in the ML pipeline, whenever we want to train models with process/authorship metrics.

**Comment by jan-gerling** [comment]
I would like to claim this issue.
