### ISSUE TITLE
Visit the repository once instead of twice

### ISSUE THREAD

**Issue by mauricioaniche** [mauricioaniche/predicting-refactoring-ml#25]
Right now, the tool does two visits in the repo. The first to collect instances of refactoring, and the second one to collect instances of non-refactoring.

Historically, It was like this given our first usage of RefactoringMiner. Now, it is definitely possible to do it in a single visit. 

It is hard to measure the amount of time it would save (the second execution is pretty fast), but definitely visiting each repository one less time (i.e., millions and millions of less commits visited) is beneficial in the large scale.

This is a tricky refactoring, though.

**Comment by jan-gerling** [comment]
I would like to work on this issue.

I will probably come up with some questions, though.
