### ISSUE TITLE
Test files only 

### ISSUE THREAD

**Issue by jan-gerling** [mauricioaniche/predicting-refactoring-ml#34]
In the Readme nine arguments are explained to run RunSingleProject, but the implementation only allows 8. Test files only flag is missing in the code and so is a test file filter.
* Extend the arguments in RunSingleProject, RunQueue and App
* Implement a filter to only analyze files

**Comment by mauricioaniche** [comment]
There's no "test files only" anymore. Our tool analyses both and stores a flag to whether the file is a test or not.

We should simply update it in the README file.

**Comment by mauricioaniche** [comment]
That being said, a test to make sure that the tool is indeed marking test files as tests, and production files as not tests, is good!

**Comment by jan-gerling** [comment]
> That being said, a test to make sure that the tool is indeed marking test files as tests, and production files as not tests, is good!

I will do this on the PR for this issue.
