### ISSUE TITLE
Bug - CommitMetaData Persistence

### ISSUE THREAD

**Issue by jan-gerling** [mauricioaniche/predicting-refactoring-ml#82]
The commit 58244b418bba42dc33f186cba432c4dde6cd38e6 introduced bugs:

1.All of the commit meta datas are persisted to the data base, even though only a fraction of them is needed. https://github.com/mauricioaniche/predicting-refactoring-ml/blob/b4288ebd25ca6a69275cfdbc9f16acabd34dd8f0/data-collection/src/main/java/refactoringml/ProcessMetricsCollector.java#L58-L59
This bug can be easily observed in the toyproject 3. We only have 12 relavant commits, but all 20 commits are stored.

2. In  some cases the CommitMetaData in StableCommits is null.
     Database.loadCommitMetaData returns null, in case the CommitMetaData was never persisted 
     before, e.g. when a class was never refactored.

These bugs can be observed by running the ApacheCommonsCliIntegrationTest.

**Comment by jan-gerling** [comment]
Fixed.

**Comment by mauricioaniche** [comment]
I wrote a comment in commit `cdf9a2c`
